---
# using https://github.com/docker-library/golang/blob/f441baf15c3e7397c2c3f6f712b4d4ba374f1948/1.11/stretch/Dockerfile as a reference
- name: install package dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - g++
    - gcc
    - libc6-dev
    - make
    - pkg-config
  become: yes
- name: download golang
  get_url:
    url: "{{ golang_url }}"
    dest: "/tmp/{{ golang_filename }}"
    checksum: "sha256:{{ golang_sha256 }}"
  become: yes
- name: unarchive golang
  unarchive:
    src: "/tmp/{{ golang_filename }}"
    dest: "/usr/local"
  become: yes
- name: create go workdirs
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /go/src
    - /go/bin
  become: yes
- name: set up /etc/environment for golang
  lineinfile:
    path: /etc/environment
    line: "{{ item }}"
  with_items:
    - GOPATH="/go"
    - PATH="/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
  become: yes
